### ISSUE TITLE
IE8 not supporting HTMLElement

### ISSUE THREAD

**Issue by dominik-bln** [lazd/scopedQuerySelectorShim#4]
I'm running into problems with this polyfill in IE8, which doesn't support HTMLElement, but does support querySelectorAll. A solution that seems to work on IE8 is to shim HTMLElement to Element in the beginning of the script like so:

``` javascript
// for older browsers that don't support HTMLElement but querySelectorAll (like IE8)
if(typeof HTMLElement === 'undefined'){
  HTMLElement = Element;  
}
```

Not sure about the consequences on other browsers though.

**Comment by WebReflection** [comment]
@dominik-bln I suggest you include this poly for IE8 upfront:
https://github.com/WebReflection/ie8#ie8-in-cdn
