### ISSUE TITLE
Npm install available?

### ISSUE THREAD

**Issue by joetidee** [lazd/scopedQuerySelectorShim#9]

**Comment by Gi60s** [comment]
You could just do: npm install lazd/scopedQuerySelectorShim

**Comment by joetidee** [comment]
and use what import?

**Comment by Gi60s** [comment]
Hmm. Good question.

**Comment by franktopel** [comment]
@lazd Some information from your side would be helpful here.

**Comment by lazd** [comment]
@franktopel Looks like others figured it out and failed to report back. The following works: ```require('scopedQuerySelectorShim/src/scopedQuerySelectorShim.js')```

That said, I just pushed a commit that has an `index.js` file that points to the shim. You can now do:

```
require('scopedQuerySelectorShim');
```
